In [70]:
import torch
import pandas as pd
import numpy as np 


In [71]:
df = pd.read_csv(r"D:\anup\pytorch_learn\Datasets\data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [72]:
df.shape

(569, 33)

In [73]:
df1 = df.drop(columns =["id", "Unnamed: 32"])
df1

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           M        17.99         10.38          122.80     1001.0   
1           M        20.57         17.77          132.90     1326.0   
2           M        19.69         21.25          130.00     1203.0   
3           M        11.42         20.38           77.58      386.1   
4           M        20.29         14.34          135.10     1297.0   
..        ...          ...           ...             ...        ...   
564         M        21.56         22.39          142.00     1479.0   
565         M        20.13         28.25          131.20     1261.0   
566         M        16.60         28.08          108.30      858.1   
567         M        20.60         29.33          140.10     1265.0   
568         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...         

In [74]:
# train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df1.iloc[:,1:],df1.iloc[:,0], test_size = 0.2)

In [75]:
print(df1.shape)            # Check number of rows & columns
print(df1.iloc[:, 1:].head())  # Check features
print(df1.iloc[:, 0].head())   # Check target



(569, 31)
   radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   fractal_dimension_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0 

In [76]:
#importing standard scaler and Scaling feature 

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [77]:
X_train

array([[-0.12029546,  1.23347297, -0.01711503, ...,  0.5547228 ,
         1.23161711,  1.91700083],
       [ 1.7907423 ,  0.46936026,  1.84113853, ...,  1.45702439,
        -0.66437328,  0.36740867],
       [-1.29260563, -0.17719664, -1.27747438, ..., -0.76367395,
         0.45929652,  0.10740998],
       ...,
       [-0.19933395, -1.14820755, -0.21614064, ...,  0.19959396,
         0.14032973, -0.58500757],
       [ 2.53031673,  1.81654974,  2.48276115, ...,  2.18862027,
         0.34433894,  0.19115693],
       [ 1.75686866,  0.33534665,  1.71444871, ...,  0.69494534,
         0.53377607, -1.06285778]])

In [78]:
X_test


array([[-0.2444988 ,  2.69821824, -0.26191245, ..., -0.58031773,
        -1.12420357, -0.35730346],
       [ 0.36240388,  3.36593519,  0.44755053, ...,  1.30613274,
         1.00655933,  2.03194761],
       [-0.22191638, -0.11606762, -0.216958  , ...,  0.41145194,
         1.01627405,  0.18458854],
       ...,
       [ 0.2918338 ,  0.74444084,  0.25220301, ...,  0.10509616,
         0.46091564,  0.79052232],
       [-0.69050171, -0.6262598 , -0.56228992, ...,  1.07903318,
         4.66901046,  1.07953138],
       [ 3.66226081,  0.61748057,  3.65157689, ...,  2.33341529,
        -0.05558388, -0.13452564]])

In [79]:
y_train


501    M
499    M
470    B
523    B
267    B
      ..
302    M
377    B
19     B
236    M
533    M
Name: diagnosis, Length: 455, dtype: object

In [80]:
y_test

455    B
259    M
526    B
413    B
40     M
      ..
374    B
195    B
184    M
146    M
180    M
Name: diagnosis, Length: 114, dtype: object

In [81]:
# label encoding 
from sklearn.preprocessing import LabelEncoder
encoder= LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [82]:
y_train

array([1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,

### converting numpy arrays to Pytorch tensors 

In [83]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [84]:
X_train_tensor

tensor([[-0.1203,  1.2335, -0.0171,  ...,  0.5547,  1.2316,  1.9170],
        [ 1.7907,  0.4694,  1.8411,  ...,  1.4570, -0.6644,  0.3674],
        [-1.2926, -0.1772, -1.2775,  ..., -0.7637,  0.4593,  0.1074],
        ...,
        [-0.1993, -1.1482, -0.2161,  ...,  0.1996,  0.1403, -0.5850],
        [ 2.5303,  1.8165,  2.4828,  ...,  2.1886,  0.3443,  0.1912],
        [ 1.7569,  0.3353,  1.7144,  ...,  0.6949,  0.5338, -1.0629]],
       dtype=torch.float64)

In [85]:
X_train_tensor.shape

torch.Size([455, 30])

In [86]:
y_train_tensor

tensor([1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
        0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
        1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
        1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
        0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
        1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
        1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,

In [87]:
y_train_tensor.shape

torch.Size([455])

### Defining the Model

In [112]:
# structuring the model 

class MySimpleNN():
    def __init__(self,X):
        self.weights = torch.rand(X.shape[1], 1, dtype= torch.float64, requires_grad = True)
        self.bias = torch.zeros(1, dtype = torch.float64, requires_grad= True)

    def forward(self,X):
        z = torch.matmul(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    def loss_function(self, y_pred, y):
        # using clamp to avoid log(0)
        epsilon = 1e-8
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
        # calculate loss 
        loss = -(y * torch.log(y_pred) + (1- y_train_tensor) + torch.log(1-y_pred)).mean()
        return loss

In [113]:
learning_rate = 0.1
epochs = 25

### training pipeline

In [114]:
#create pipeline
model = MySimpleNN(X_train_tensor)
model.weights
# define loop 
for epoch in range(epochs):
#forward pass
    y_pred = model.forward(X_train_tensor)
    # print(y_pred)
# loss calculate
    loss = model.loss_function(y_pred, y_train_tensor)
   
# backward pass
    loss.backward()
# parameter update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -=learning_rate * model.bias.grad

# zero gradients 
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    print(f'Epoch: {epoch +1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.1020543869449098
Epoch: 2, Loss: 2.9791039660508947
Epoch: 3, Loss: 2.8481986810546958
Epoch: 4, Loss: 2.7082298127231996
Epoch: 5, Loss: 2.5613972896747685
Epoch: 6, Loss: 2.413563905647041
Epoch: 7, Loss: 2.2603464443640746
Epoch: 8, Loss: 2.0947466634742207
Epoch: 9, Loss: 1.924908890643885
Epoch: 10, Loss: 1.7508584571785277
Epoch: 11, Loss: 1.5687921130864058
Epoch: 12, Loss: 1.3818009521217218
Epoch: 13, Loss: 1.2028130498918121
Epoch: 14, Loss: 1.029380885106198
Epoch: 15, Loss: 0.8701398933988713
Epoch: 16, Loss: 0.7273661500456742
Epoch: 17, Loss: 0.6030190051135076
Epoch: 18, Loss: 0.4983209474244357
Epoch: 19, Loss: 0.41331791815422647
Epoch: 20, Loss: 0.3466387298361963
Epoch: 21, Loss: 0.2956847494045251
Epoch: 22, Loss: 0.257235835877759
Epoch: 23, Loss: 0.2281497546865286
Epoch: 24, Loss: 0.2058159373584276
Epoch: 25, Loss: 0.1882814007488278


In [115]:
model.bias

tensor([-0.7105], dtype=torch.float64, requires_grad=True)

### model evaluation 

In [116]:
# model evaluation 
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred =(y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.7456140518188477


In [111]:
import torch
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Load Dataset
df = pd.read_csv(r"D:\anup\pytorch_learn\Datasets\data.csv")
df1 = df.drop(columns=["id", "Unnamed: 32"])  # Drop unnecessary columns

# Split Features & Labels
X_train, X_test, y_train, y_test = train_test_split(df1.iloc[:, 1:], df1.iloc[:, 0], test_size=0.2, random_state=42)

# Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Encode Labels
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

# Convert to Tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float64, requires_grad=False)
X_test_tensor = torch.tensor(X_test, dtype=torch.float64, requires_grad=False)
y_train_tensor = torch.tensor(y_train, dtype=torch.float64, requires_grad=False).view(-1, 1)
y_test_tensor = torch.tensor(y_test, dtype=torch.float64, requires_grad=False).view(-1, 1)

# Define Neural Network
class MySimpleNN():
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)  # Apply sigmoid activation
        return y_pred

    def loss_function(self, y_pred, y):
        epsilon = 1e-8  # Avoid log(0)
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
        loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
        return loss

# Hyperparameters
learning_rate = 0.3
epochs = 25

# Initialize Model
model = MySimpleNN(X_train_tensor)

# Training Loop
for epoch in range(epochs):
    # Forward Pass
    y_pred = model.forward(X_train_tensor)

    # Compute Loss
    loss = model.loss_function(y_pred, y_train_tensor)

    # Backward Pass
    loss.backward()

    # Update Weights & Bias
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # Zero Gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # Print Loss
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

# Model Evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()  # Apply 0.5 threshold
    accuracy = y_pred.eq(y_test_tensor).float().mean()  # Compute accuracy
    print(f'Accuracy: {accuracy.item()}')


Epoch: 1, Loss: 0.6320169132026717
Epoch: 2, Loss: 0.5831565606323232
Epoch: 3, Loss: 0.5377445390463789
Epoch: 4, Loss: 0.49558296252872114
Epoch: 5, Loss: 0.4566242603140151
Epoch: 6, Loss: 0.4208135988692827
Epoch: 7, Loss: 0.3879015121326589
Epoch: 8, Loss: 0.3549036580497467
Epoch: 9, Loss: 0.320072562310264
Epoch: 10, Loss: 0.28802032922539456
Epoch: 11, Loss: 0.2590021055842213
Epoch: 12, Loss: 0.233331557923012
Epoch: 13, Loss: 0.21112217051968107
Epoch: 14, Loss: 0.19215736285512502
Epoch: 15, Loss: 0.17600034974134465
Epoch: 16, Loss: 0.16218504875961393
Epoch: 17, Loss: 0.15032622720901484
Epoch: 18, Loss: 0.14014478778896805
Epoch: 19, Loss: 0.13145332133178653
Epoch: 20, Loss: 0.1241273659238058
Epoch: 21, Loss: 0.11807101591986995
Epoch: 22, Loss: 0.11317909759186605
Epoch: 23, Loss: 0.10930451068021536
Epoch: 24, Loss: 0.10625573701836231
Epoch: 25, Loss: 0.10383249909500705
Accuracy: 0.9736841917037964


In [117]:
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Load dataset
df = pd.read_csv(r"D:\anup\pytorch_learn\Datasets\data.csv")
df.drop(columns=["id", "Unnamed: 32"], inplace=True)  # Remove unnecessary columns

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2, random_state=42)

# Standardizing features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Encoding labels
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

# Convert to PyTorch tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)

# Define Neural Network
class MySimpleNN(nn.Module):
    def __init__(self, input_dim):
        super(MySimpleNN, self).__init__()
        self.linear = nn.Linear(input_dim, 1)
    
    def forward(self, x):
        return torch.sigmoid(self.linear(x))

# Initialize model, loss, and optimizer
model = MySimpleNN(X_train.shape[1])
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Training loop
epochs = 25
for epoch in range(epochs):
    optimizer.zero_grad()
    y_pred = model(X_train_tensor)
    loss = criterion(y_pred, y_train_tensor)
    loss.backward()
    optimizer.step()
    print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}")

# Model Evaluation
model.eval()
with torch.no_grad():
    y_pred_test = model(X_test_tensor)
    y_pred_labels = (y_pred_test > 0.5).float()
    
    accuracy = accuracy_score(y_test, y_pred_labels.numpy())
    precision = precision_score(y_test, y_pred_labels.numpy())
    recall = recall_score(y_test, y_pred_labels.numpy())
    f1 = f1_score(y_test, y_pred_labels.numpy())
    conf_matrix = confusion_matrix(y_test, y_pred_labels.numpy())
    
    print(f"Accuracy: {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1 Score: {f1:.4f}")
    print(f"Confusion Matrix:\n{conf_matrix}")

# Save predictions for Kaggle submission
df_predictions = pd.DataFrame({"Actual": y_test, "Predicted": y_pred_labels.numpy().flatten()})
df_predictions.to_csv("predictions.csv", index=False)
print("Predictions saved to predictions.csv")

Epoch 1/25, Loss: 0.6587
Epoch 2/25, Loss: 0.6007
Epoch 3/25, Loss: 0.5497
Epoch 4/25, Loss: 0.5046
Epoch 5/25, Loss: 0.4651
Epoch 6/25, Loss: 0.4303
Epoch 7/25, Loss: 0.3998
Epoch 8/25, Loss: 0.3731
Epoch 9/25, Loss: 0.3495
Epoch 10/25, Loss: 0.3287
Epoch 11/25, Loss: 0.3102
Epoch 12/25, Loss: 0.2938
Epoch 13/25, Loss: 0.2790
Epoch 14/25, Loss: 0.2657
Epoch 15/25, Loss: 0.2538
Epoch 16/25, Loss: 0.2429
Epoch 17/25, Loss: 0.2330
Epoch 18/25, Loss: 0.2240
Epoch 19/25, Loss: 0.2158
Epoch 20/25, Loss: 0.2082
Epoch 21/25, Loss: 0.2013
Epoch 22/25, Loss: 0.1949
Epoch 23/25, Loss: 0.1890
Epoch 24/25, Loss: 0.1836
Epoch 25/25, Loss: 0.1786
Accuracy: 0.9737
Precision: 0.9545
Recall: 0.9767
F1 Score: 0.9655
Confusion Matrix:
[[69  2]
 [ 1 42]]
Predictions saved to predictions.csv
